# Generated by Django 3.0.6 on 2020-05-31 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_customplanprices_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customplanprices',
            name='custom_plan',
        ),
        migrations.AddField(
            model_name='customplanprices',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customplanprices',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomPlan',
        ),
    ]
