# Generated by Django 3.0.6 on 2020-07-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20200531_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='provider_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='ID сервиса у провайдера'),
        ),
    ]
