# Generated by Django 3.0.6 on 2020-05-31 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='a_field',
            field=models.CharField(blank=True, max_length=24, verbose_name='A'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='api_token',
            field=models.CharField(blank=True, max_length=58),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний визит'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.CustomUserSite', verbose_name='Сайт'),
        ),
    ]
