# Generated by Django 3.0.6 on 2020-06-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200626_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='amount',
            new_name='_amount',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='_amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, default=0, max_digits=9, verbose_name='Сумма'),
        ),
    ]
