# Generated by Django 3.0.6 on 2020-06-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200627_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='_amount',
            new_name='amount',
        ),
    ]
