# Generated by Django 3.0.6 on 2020-06-25 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0003_auto_20200531_2253'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField(blank=True, max_length=24)),
                ('name', models.CharField(max_length=128)),
                ('amount', models.IntegerField(blank=True, max_length=24, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена, руб.')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Возврат, руб.')),
                ('start_count', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('remains', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.Plan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
