# Generated by Django 3.0.6 on 2020-07-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider_id',
            field=models.IntegerField(blank=True, max_length=24, null=True),
        ),
    ]
