# Generated by Django 3.0.6 on 2020-07-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200704_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remains',
            field=models.IntegerField(blank=True, max_length=24, null=True),
        ),
    ]
