# Generated by Django 3.0.6 on 2020-07-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200704_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='countries',
            field=models.CharField(default='russia', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='traffic',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='video',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
